### ISSUE TITLE
getDisplayName is returning wrong name

### ISSUE THREAD

**Issue by NirmalPrajapat** [4Q-s-r-o/call_log#20]
Name/Display Name in call log entry is always same for both SIM cards even I have different SIM cards.
Eg. I have Vodafone in slot 1 and Airtel in slot 2. When I try to get the call logs in android it shows Vodafone as SimDisplayName for all entries form both SIM cards.

I debug and found that subscriberId/PhoneAccountId containing alphabet('F' in my case) in the end. I saw you code at CallLogPlugin.java (Line:215) Integer.toString(info.getSubscriptionId()).equals(accountId), if subId contains alphabet in the end then Integer.toString won't work.
Please suggest any possible fix for this.

Thanks

**Comment by MartinHlavna** [comment]
Hi,

It as actually other way around. ```info.getSubscriptionId()``` will return Integer and we convert that to string to compare with accountId. 

Maybe accountId contains "F"? And getSubscriptionId will return the same value without alphabet chars? If that is the case, maybe we could strip any alphabet chars from accountId. Since we cannot reproduce this issue, can you please confirm this?

**Comment by MartinHlavna** [comment]
Closing because of no response from reporter. If problem persists, please feel free to reopen with requested information.

**Comment by Johnny-Silverhand-47** [comment]
I have the same issue still, only the name of sim in first slot is being returned in all calls
