### ISSUE TITLE
google play rejected app

### ISSUE THREAD

**Issue by Cakaros** [4Q-s-r-o/call_log#22]
I am getting a rejection from google play with the code you shared. Can you help me what should I do to get my application approved?

Thanks,

**Comment by ethael** [comment]
Call log access is restricted to only those applications which need to use it as its primary functionality. E.G. Phone application, otherwise it will be rejected. More details can be seen on Google's official documentation:

https://support.google.com/googleplay/android-developer/answer/10208820?hl=en#zippy=

**Comment by varunkudalkar** [comment]
@Cakaros Any updates on your application? is your application approved by the google play store?

**Comment by AhmedHussein22** [comment]
**[Try This Way](https://stackoverflow.com/questions/54838468/google-play-store-rejected-my-app-due-to-sms-permission)**
I also had this problem, I removed sms permissions in manifest,I tried whole day its rejected again and again, so I deleted all part of the code and I published only splash screen and login page, so my app is successfully published, and I updated my full project in next version, my application is live now.
