### ISSUE TITLE
Add flag to set check permissions automatically

### ISSUE THREAD

**Issue by varunkudalkar** [4Q-s-r-o/call_log#24]
I am working on a default phone app for android and my application is getting rejected because this plugin adding READ_CALL_LOG permission request in the manifest by default, if m application doesn't want to ask for permissions to the user then in my application I can set check permission automatic flag as false.

Currently, as the document suggests `This plugin is able to handle checking and requesting permission automatically`. I am not able to remove the READ_CALL_LOG permission.

**Comment by MartinHlavna** [comment]
Hi,

https://developer.android.com/training/permissions/requesting

Any permission that app could ask for needs to be in Manifest AFAIK. Without these permission the plugin will not work. Since you are making the phone app, Google should not reject your application. 

Are you declaring permission in play console?

https://support.google.com/googleplay/android-developer/answer/10208820?hl=en#zippy=,exceptions
